### ISSUE TITLE
bob_new_version.py misses a good "default" for version numbers

### ISSUE THREAD

**Issue by anjos** [bioidiap/bob.extension#6] opened 2016-01-25 12:24 UTC
This is a **very** useful script. It would be an awesome addition if we could have either a flag (or the absence of any) to implement a "default" version releasing.

How would that work?

1. bob_new_version.py reads the file `version.txt` and figures out what is the "next" release.
2. It sets the stable version to that value (minus the `aX`, `bX` or `rcX` complements, of course).
3. It sets the latest version to be the value in item 2 above + one minor patch number. For example, if the value on `version.txt` was '2.0.5b0', then `stable = 2.0.5` and `latest = 2.0.6b0`.

This way it would be possible to issue something like:

```shell
$ ./bin/bob_new_version.py --default-release
```

And get the ball rolling. This would also allow us to batch release a number of packages at once, w/o taking into consideration differences between release numbers.

If a new API release is on the horizon, the developer must updated "version.txt" so that the file `version.txt` is correctly preset (e.g., to `2.1.0b0`). This way `bob_new_version.py --default-release` will do the right thing next time.

@siebenkopf: What do you think?

**Comment by siebenkopf** [comment] 2016-01-25 16:13
I am not sure to understand, what is your issue. What exactly should the ``--default-release`` flag do?

What I think you mean is that by default, only the patch level (last digit) is increased (A.B.C -> A.B.(C+1)), while you want to be able to increase the major -> (A+1).0.0 or minor A.(B+1).C version. For this purpose, I would rather recommend a flag like ``--version-level`` which excepts ``'major', 'minor'`` or ``'patch'``.

Is this what you mean?

**Comment by anjos** [comment] 2016-01-25 16:36
I meant that, by default, only `(A.B.C -> A.B.(C+1))` happens.

If you need to make sure that `B -> (B+1)`, then the only action you need to do is:

```shell
$ cat '2.1.0a0' >> version.txt
```

This is anyways logical once you have updated the API, so, even if the new_version script is not called, we should be doing this. Now, if you call:

```shell
$ bob_new_version.py --default-release
```

This will already do the right thing, given `version.txt` contains already `2.1.0a`, which means the next stable is `2.1.0` and the next latest is `2.1.1a0`.

Right?

**Comment by anjos** [comment] 2016-01-25 16:43
BTW: bob.core had an API change and we didn't pay attentation to the `version.txt` file. The end result was that it was released as version `2.0.5` instead of version `2.1.0` as it should.

Here is the moral: the person doing the release cannot possibly look into all packages for API changes, so they just blindly updated the release number (i.e., do the C+1 thingy). The person doing the API change must also commit a new `version.txt` file with the next reasonable release name.

If we follow this policy, then `bob_new_version.py --default-release` stays rather simple (only worries about `C` changes) and the person doing the API change bumps the number.

**Comment by siebenkopf** [comment] 2016-01-25 16:45
I still don't get what you mean. There is no ``--default-release`` flag yet, and I still don't see, why this should be better than introducing a ``--version-level`` flag, where you can specify exactly, which version (A,B, or C) you want to increase.

By default, the script increases C, independent on what A or B are. There is no need for a ``--default-release`` flag, as I don't see, how this should change the default behavior.

**Comment by siebenkopf** [comment] 2016-01-25 16:47
I agree that, if you change the API in the master branch, you are responsible to increase the ``version.txt``. I apologize if I forgot to do that in bob.core (if it was me).

**Comment by anjos** [comment] 2016-01-25 16:49
Very well, if you agree the developer making an API change should handle the `version.txt` file, then we have no need for anything else than incrementing the patch level value, right?

Let me go through another way: in which condition will you make such a significant change on your package and *NOT* set `version.txt`?

It follows that, if you do follow the policy, then the next `latest` version is always increased on C and never on A or B.

**Comment by siebenkopf** [comment] 2016-01-25 17:13
Yes, that is what the script was intended to do: always increase the patch level (C), and never the major (A) or minor (B) versions. It should be up to the developer to decide, when it is time to increase A or B inside the ``version.txt`` by hand.

In fact, in each commit you factually should touch the ``version.txt``, in most cases just increasing the very last digit (X) of A.B.CbX. I can understand that people are too lazy to do that, as I am too lazy, too.
Anyways, at least when you do API changes, you definitely should increase the ``version.txt`` manually.

Now, AFAIR, in ``bob.core`` I was developing the new API in a new branch, where I actually increased the version in ``version.txt`` manually. However, during the merge, the change in the ``version.txt`` got lost, as it was increased in the master branch as well, but to another patch value, not increasing the minor version. 
Anyways, I have to be more careful when uploading new versions (using the new_version.py script), especially when I have manually edited the ``version.txt``.

**Comment by siebenkopf** [comment] 2016-01-25 17:36
So, I assume that nothing has to be done according to this issue, and I close it.

**Comment by anjos** [comment] 2016-01-25 20:37
I'm sorry there **is** something to be done, unless, you tell me there is some sort of "smart" mode on the `new_version` script that requires no flags - is there?

Otherwise, now that we have developed the subject and agreed on the development procedure, please re-read the first comment carefully, including the "batch" mode issue.

**Comment by siebenkopf** [comment] 2016-01-25 20:42
Indeed, the script by default requires no flags, and the versions are estimated based on what is read from the ``version.txt``. Hence:

```
$ bob_new_version.py -vv
```

should do the trick. You can try it out using the ``--dry-run`` flag

```
$ bob_new_version.py -vvq
```

**Comment by anjos** [comment] 2016-01-25 20:43
Awesome! It was just my ignorance on the script's capabilities then! Cheers, A

**Comment by anjos** [comment] 2016-01-25 20:45
Actually, there is 1 improvement to be done: improve the help message as to explain the "natural" way to use the script. As of today, the help message indicates only how to use it by setting the stable and the latest versions, but that should not be the "default", right?

**Comment by siebenkopf** [comment] 2016-01-25 20:45
Maybe you still had an older version of the script, where this was indeed not possible. But I have implemented the default version handling already some time ago:
f96859a2fecd9ec0511451c591633de483f6e983

**Comment by anjos** [comment] 2016-01-25 20:46
I confirm that, even in the latest, the help message does not indicate how to use it in the most obvious way.

**Comment by siebenkopf** [comment] 2016-01-25 21:52
@anjos You just don't want your bug to marked as invalid, and you do not give up until you find something, might it be as little as a documentation issue ;-)

In fact, the docs say that ``Both versions can be automatically computed from the current version, which is stored in the 'version.txt' file``, they do not say that this is default behavior. I will fix that.

**Closed** 2016-01-25 22:15 UTC

**Comment by anjos** [comment] 2016-01-26 09:05
Thanks - It actually took me the whole day yesterday to figure this out, thanks to your help. It was a very useful addition to make it clear on the help message this is the case.
